[package]
name = "pacode-plugin"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
pacode-types = { workspace = true }
mlua = { workspace = true }
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }

tokio = { workspace = true, features = ["rt", "sync", "time"] }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
dirs = { workspace = true }
log = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
